export const projects = [
    {
        id: 1,
        title: "projects.1.title",
        desc: "projects.1.desc",
        img: "src/assets/img/projects/marvel-dc-app.jpg",
        tools: ["React", "Redux", "Node.js", "MongoDB", "Express", "Heroku", "Netlify"],
        demo: "https://omarvd-code.github.io/marvel-dc-comic/#/home",
        code: "https://github.com/OmarVD-code/marvel-dc-comic",
        is_code_available: true,
    },
    {
        id: 2,
        title: "projects.2.title",
        desc: "projects.2.desc",
        img: "src/assets/img/projects/imgshare.png",
        tools: ["React", "Redux", "Node.js", "MongoDB", "Express", "Heroku", "Netlify"],
        demo: "https://imgshare-socialmedia.herokuapp.com/",
        code: "https://github.com/OmarVD-code/redsocial-mongodb",
        is_code_available: true,
    },
    {
        id: 3,
        title: "projects.3.title",
        desc: "projects.3.desc",
        img: "src/assets/img/projects/project-amg.png",
        tools: ["Vue.js", "Laravel", "NestJS"],
        demo: "https://www.front.amgsoft.us/",
        code: "https://github.com/OmarVD-code/DogWebApp",
        is_code_available: false,
    },
];