export const projects = [
    {
        id: 1,
        title: "Project 1",
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. Lorem Ipsum has been the industry's standard dummy text. Continue typing just to see if this fits.",
        img: "src/assets/img/projects/marvel-dc-app.jpg",
        tools: ["React", "Redux", "Node.js", "MongoDB", "Express", "Heroku", "Netlify"],
        demo: "https://omarvd-code.github.io/marvel-dc-comic/#/home",
        code: "https://github.com/OmarVD-code/marvel-dc-comic",
        isCodeAvailable: true,
    },
    {
        id: 2,
        title: "Project 2",
        desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. Lorem Ipsum has been the industry's standard dummy text. Continue typing just to see if this fits.",
        img: "src/assets/img/projects/imgshare.png",
        tools: ["React", "Redux", "Node.js", "MongoDB", "Express", "Heroku", "Netlify"],
        demo: "https://imgshare-socialmedia.herokuapp.com/",
        code: "https://github.com/OmarVD-code/redsocial-mongodb",
        isCodeAvailable: true,
    },
    {
        id: 3,
        title: "AMG SOFT",
        desc: "I worked for over 3 years on this large internal enterprise system used to manage multiple core business processes across the company. The project was a long-term product developed through continuous iterations and agile sprints. My role involved developing new features, enhancing existing modules, maintaining production code, and optimizing database queries to improve performance and stability. The system was built using Vue.js on the frontend, with Laravel and NestJS powering backend services and APIs.",
        img: "src/assets/img/projects/project-amg.png",
        tools: ["Vue.js", "Laravel", "NestJS"],
        demo: "https://www.front.amgsoft.us/",
        code: "https://github.com/OmarVD-code/DogWebApp",
        isCodeAvailable: false,
    },
];