export const projects = [
    {
        id: 1,
        title: "projects.1.title",
        desc: "projects.1.desc",
        img: "src/assets/img/projects/project-amg.png",
        tools: ["Vue.js", "Laravel", "NestJS", "TypeScript", "MySQL", "MongoDB", "AWS Lambda", "AWS Amplify"],
        demo: "https://www.front.amgsoft.us/",
        code: "",
        is_code_available: false,
    },
    {
        id: 2,
        title: "projects.2.title",
        desc: "projects.2.desc",
        img: "src/assets/img/projects/project-portfolio.png",
        tools: ["React", "TypeScript", "Vite", "CSS Animations", "i18n", "UX/UI"],
        demo: "https://imgshare-socialmedia.herokuapp.com/",
        code: "https://github.com/OmarVD-code/redsocial-mongodb",
        is_code_available: true,
    },
    {
        id: 3,
        title: "projects.3.title",
        desc: "projects.3.desc",
        img: "src/assets/img/projects/project-amg.png",
        tools: ["Vue.js", "Laravel", "NestJS"],
        demo: "https://www.front.amgsoft.us/",
        code: "https://github.com/OmarVD-code/DogWebApp",
        is_code_available: false,
    },
];